src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChambreRepository::class)
 */
class Chambre
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_chambre;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity=Etudiant::class, mappedBy="chambre")
     */
    private $etudiants;

    public function __construct()
    {
        $this->etudiants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroChambre(): ?string
    {
        return $this->numero_chambre;
    }

    public function setNumeroChambre(string $numero_chambre): self
    {
        $this->numero_chambre = $numero_chambre;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|Etudiant[]
     */
    public function getEtudiants(): Collection
    {
        return $this->etudiants;
    }

    public function addEtudiant(Etudiant $etudiant): self
    {
        if (!$this->etudiants->contains($etudiant)) {
            $this->etudiants[] = $etudiant;
            $etudiant->setChambre($this);
        }

        return $this;
    }

    public function removeEtudiant(Etudiant $etudiant): self
    {
        if ($this->etudiants->contains($etudiant)) {
            $this->etudiants->removeElement($etudiant);
            // set the owning side to null (unless already changed)
            if ($etudiant->getChambre() === $this) {
                $etudiant->setChambre(null);
            }
        }

        return $this;
    }
}

src/Form/ChambreType.php
<?php

namespace App\Form;

use App\Entity\Chambre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChambreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numero_chambre')
            ->add('type')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Chambre::class,
        ]);
    }
}

src/Controller/ChambreController.php
<?php

namespace App\Controller;

use App\Entity\Chambre;
use App\Form\ChambreType;
use App\Repository\ChambreRepository;

use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Bundle\PaginatorBundle\KnpPaginatorBundle;
/**
 * @Route("/chambre")
 */
class ChambreController extends AbstractController
{
    /**
     * @Route("/chambre", name="chambre_index", methods={"GET"})
     * @param ChambreRepository $chambreRepository

     * @param Request $request
     * @return Response
     */
    public function index(ChambreRepository $chambreRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $allChambres= $chambreRepository->findAll();
        $chambres = $paginator->paginate(
            $allChambres, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            3 /*limit per page*/
        );
        return $this->render('chambre/index.html.twig', [
            'chambres' => $chambres,
        ]);
    }

    /**
     * @Route("/new", name="chambre_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $chambre = new Chambre();
        $form = $this->createForm(ChambreType::class, $chambre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($chambre);
            $entityManager->flush();

            return $this->redirectToRoute('chambre_index');
        }

        return $this->render('chambre/new.html.twig', [
            'chambre' => $chambre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="chambre_show", methods={"GET"})
     */
    public function show(Chambre $chambre): Response
    {
        return $this->render('chambre/show.html.twig', [
            'chambre' => $chambre,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="chambre_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Chambre $chambre): Response
    {
        $form = $this->createForm(ChambreType::class, $chambre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('chambre_index');
        }

        return $this->render('chambre/edit.html.twig', [
            'chambre' => $chambre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="chambre_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Chambre $chambre): Response
    {
        if ($this->isCsrfTokenValid('delete'.$chambre->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($chambre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('chambre_index');
    }
}

templates/chambre/_delete_form.html.twig
<form method="post" action="{{ path('chambre_delete', {'id': chambre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ chambre.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/chambre/_form.html.twig
<div class="container register-form">
    <div class="form">
        <h2> <a href="{{ path('chambre_index') }}">liste de Chambres</a></h2>
        <div class="note">

            <h1>Creation des chambres</h1>
        </div>

        <div class="form-content">

            <div class="row">

                <div class="col-md-6">
                    {{ form_start(form) }}
                    <div class="form-group">
                        {{ form_row(form.numero_chambre) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.type) }}
                    </div>
                </div>

            </div>
            <button class="btn btn-success">{{ button_label|default('Enregistere') }}</button>
            {{ form_end(form) }}
        </div>
    </div>
</div>

templates/chambre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Chambre{% endblock %}

{% block body %}
    <h1>Edit Chambre</h1>

    {{ include('chambre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('chambre_index') }}">back to list</a>

    {{ include('chambre/_delete_form.html.twig') }}
{% endblock %}

templates/chambre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-8" >
                <h2 >Listes des Etudiant </h2>
            </div>
            <div class="col-sm-4">
                <a href="{{ path('chambre_new') }}">Create new Chambre</a>
            </div>
        </div>
            <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">

        <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
        <thead class="table-dark">
            <tr>
                <th>Id</th>
                <th>Numero_chambre</th>
                <th>Type</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for chambre in chambres %}
            <tr>
                <td class="bg-secondary">{{ chambre.id }}</td>
                <td class="bg-active">{{ chambre.numeroChambre }}</td>
                <td>{{ chambre.type }}</td>
                <td>
                    <a href="{{ path('chambre_delete', {'id': chambre.id}) }}">Delete</a>
                    <a href="{{ path('chambre_edit', {'id': chambre.id}) }}">Update</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
        {# display navigation #}
        <div class="navigation">
            {{ knp_pagination_render(chambres) }}
        </div>


    </div>
        <div class="col-sm-2"> </div>
</div>
    </div>
{% endblock %}

templates/chambre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Chambre{% endblock %}

{% block body %}
    <a href="{{ path('chambre_index') }}">liste de Chambres</a>
    {{ include('chambre/_form.html.twig') }}


{% endblock %}

templates/chambre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chambre{% endblock %}

{% block body %}
    <h1>Chambre</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ chambre.id }}</td>
            </tr>
            <tr>
                <th>Numero_chambre</th>
                <td>{{ chambre.numeroChambre }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ chambre.type }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('chambre_index') }}">back to list</a>

    <a href="{{ path('chambre_edit', {'id': chambre.id}) }}">edit</a>

    {{ include('chambre/_delete_form.html.twig') }}
{% endblock %}