src/Entity/Etudiant.php
<?php

namespace App\Entity;

use App\Repository\EtudiantRepository;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EtudiantRepository::class)
 */
class Etudiant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $matricule;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @Assert\Regex(
     *     pattern = "/^7[0678]{1}[0-9]{7}+$/",
     *     message= "Numero de telephone '{{ value }}' Invalider!!!!"
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     *@Assert\Regex(
     *     pattern = "/^[+a-zA-Z._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i",
     *     message= " le '{{ value }}' N'est pas un bon Adresse Email!!!!"
     * )
     * @ORM\Column(type="string", length=255)

     */
    private $email;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_etudiant;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type_bourse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adrese;

    /**
     * @ORM\ManyToOne(targetEntity=Chambre::class, inversedBy="etudiants")
     */
    private $chambre;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getTypeEtudiant(): ?string
    {
        return $this->type_etudiant;
    }

    public function setTypeEtudiant(string $type_etudiant): self
    {
        $this->type_etudiant = $type_etudiant;

        return $this;
    }

    public function getTypeBourse(): ?string
    {
        return $this->type_bourse;
    }

    public function setTypeBourse(?string $type_bourse): self
    {
        $this->type_bourse = $type_bourse;

        return $this;
    }

    public function getAdrese(): ?string
    {
        return $this->adrese;
    }

    public function setAdrese(?string $adrese): self
    {
        $this->adrese = $adrese;

        return $this;
    }

    public function getChambre(): ?Chambre
    {
        return $this->chambre;
    }

    public function setChambre(?Chambre $chambre): self
    {
        $this->chambre = $chambre;

        return $this;
    }
}

src/Form/EtudiantType.php
<?php

namespace App\Form;

use App\Entity\Chambre;
use App\Entity\Etudiant;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtudiantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('matricule')
            ->add('nom')
            ->add('prenom')
            ->add('telephone')
            ->add('email')
            ->add('date_naissance')
            ->add('type_etudiant',ChoiceType::class, [
                'choices' => [
                    'Type d Etudiant' => [
                        'rien' => 'null',
                        'Boursier' => 'boursier',
                        'Non Boursier' => 'nonboursier'
                    ],
                ],
            ])
            ->add('type_bourse',ChoiceType::class, [
                'choices' => [
                    'Type de Bourse' => [
                        'rien' => 'null',
                        'Demi Boursier' => '2000',
                        'Pension' => '4000'
                    ],
                ],
                ])
            ->add('adrese')
            ->add('chambre',EntityType::class, [
                'class' => Chambre::class,
                'choice_label' => function($chambre){
                    return $chambre->getNumeroChambre()." ".$chambre->getType();
                },
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Etudiant::class,
        ]);
    }
}

src/Controller/EtudiantController.php
<?php

namespace App\Controller;

use App\Entity\Etudiant;
use App\Form\EtudiantType;
use App\Repository\EtudiantRepository;

use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Form\Extension\Core\Type\SearchType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints as Assert;





/**
 * @Route("/etudiant")
 */
class EtudiantController extends AbstractController
{
    /**
     * @Route("/", name="etudiant_index", methods={"GET"})
     */
    public function index(EtudiantRepository $etudiantRepository,PaginatorInterface $paginator,Request $request): Response
    {
        $etudiant = new Etudiant();
        $allEtudiant= $etudiantRepository->findAll();
        $etudiant = $paginator->paginate(
            $allEtudiant, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            11/*limit per page*/
        );
        return $this->render('etudiant/index.html.twig', [
            'etudiants' => $etudiant,
        ]);
    }



    /**
     * @Route ("/Search", name="Search", methods={"GET","POST"})
     */

    public function search(Request $request)
    {
        $form = $this->createFormBuilder()->add('recherche', SearchType::class)->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $em = $this->container->get('doctrine')->getManager();
            $etudiant = $em->getRepository('App\Entity\Etudiant')->search($data['recherche']);
            return $this->render('pages/etudiant/new.html.twig', [
                'etudiant' => $etudiant,
                'form' => $form->createView(),
            ]);
        }

    }
    /**
     * @Route("/new", name="etudiant_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
       // $mat=$this->maxId();
        $date=Date('yy');
        $etudiant = new Etudiant();
        $nom=$etudiant->getNom();
        $prenom=$etudiant->getPrenom();
        $cc= strtoupper (substr("$nom",0,2));
        $ll=strtoupper(substr("$prenom",-2));
        $matricule=$date."".$cc."".$ll;

        $etudiant->setMatricule($matricule);
        $form = $this->createForm(EtudiantType::class, $etudiant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($etudiant);
            $entityManager->flush();

            return $this->redirectToRoute('etudiant_index');
        }

        return $this->render('etudiant/new.html.twig', [
            'etudiant' => $etudiant,

            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="etudiant_show", methods={"GET"})
     */
    public function show(Etudiant $etudiant): Response
    {
        return $this->render('etudiant/show.html.twig', [
            'etudiant' => $etudiant,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="etudiant_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Etudiant $etudiant): Response
    {
        $form = $this->createForm(EtudiantType::class, $etudiant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('etudiant_index');
        }

        return $this->render('etudiant/edit.html.twig', [
            'etudiant' => $etudiant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="etudiant_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Etudiant $etudiant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$etudiant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($etudiant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('etudiant_index');
    }
}

templates/etudiant/_delete_form.html.twig
<form method="post" action="{{ path('etudiant_delete', {'id': etudiant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ etudiant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/etudiant/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
<div class="container register-form">
    <div class="form">
        <div class="note">
            <h1>Creation des Etudiants</h1>
        </div>
        <div class="form-content">
            <div class="row">

                <div class="col-md-6">
                    {{ form_start(form) }}
                    <div class="form-group">
                    {{ form_row(form.matricule ,{'attr':{'placeholder':"matricule"}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.nom ,{'attr':{'placeholder':"Entre votre nom"}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.prenom) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.telephone) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.email) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.date_naissance) }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_row(form.type_etudiant) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.type_bourse) }}

                    </div>
                    <div class="form-group">
                        {{ form_row(form.adrese) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.chambre) }}
                    </div>
                    <button class="btn btn-success">{{ button_label|default('Enregistere') }}</button>
                </div>
            </div>

            {{ form_end(form) }}
        </div>
    </div>

</div>

templates/etudiant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Etudiant{% endblock %}

{% block body %}
    <h1>Edit Etudiant</h1>

    {{ include('etudiant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('etudiant_index') }}">back to list</a>

    {{ include('etudiant/_delete_form.html.twig') }}
{% endblock %}

templates/etudiant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creer Etudiant{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-4 col-lg-4 col-xl-2">
                <p>Listes des Etudiant </p>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-4 col-xl--">
                <li> <a class="trigger" href="#"><i class="fas fa-search"></i></a></li>
                <div class="modal">
                    <div class="modal-content">
                        <span class="close-button">&times;</span>
                        <form action="{{ path('Search') }}" method="POST">
                            <input type="search"> <input type="submit" value="Rechercher">
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-md-4 col-lg-4 col-xl-4">
                <p style="float: right"> <a href="{{ path('etudiant_new') }}">Creer un Nouveau Etudiant</a>
                </p>
            </div>
        </div>
        <div class="row">

            <div  class="table-wrapper-scroll-y my-custom-scrollbar">

                <table id="dtBasicExample" class="table table-bordered table-striped mb-0 ">


                    <thead class="thead-dark">
                    <tr>
                        <th>Id</th>
                        <th>Matricule</th>
                        <th>Nom</th>
                        <th>Prenom</th>
                        <th>Telephone</th>
                        <th>Email</th>
                        <th>Date_naissance</th>
                        <th>Type_etudiant</th>
                        <th>Type_bourse</th>
                        <th>Adrese</th>
                        <th colspan="2">ACTION</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for etudiant in etudiants %}
                        <tr>
                            <td>{{ etudiant.id }}</td>
                            <td>{{ etudiant.matricule }}</td>
                            <td>{{ etudiant.nom }}</td>
                            <td>{{ etudiant.prenom }}</td>
                            <td>{{ etudiant.telephone }}</td>
                            <td>{{ etudiant.email }}</td>
                            <td>{{ etudiant.dateNaissance ? etudiant.dateNaissance|date('Y-m-d') : '' }}</td>
                            <td>{{ etudiant.typeEtudiant }}</td>
                            <td>{{ etudiant.typeBourse }}</td>
                            <td>{{ etudiant.adrese }}</td>
                            <td>
                                <a href="{{ path('etudiant_show', {'id': etudiant.id}) }}"
                                   style="">Show</a>  </td>
                            <td><a href="{{ path('etudiant_edit', {'id': etudiant.id}) }} ">edit</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="11">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>

                </table>
                    {# display navigation #}
                    <div class="navigation">
                        {{ knp_pagination_render(etudiants) }}
                    </div>
            </div>


        </div>
    </div>



    <script>
        $(document).ready(function () {
            $('#dtBasicExample').DataTable();
            $('.dataTables_length').addClass('bs-select');
        });
    </script>
{% endblock %}

templates/etudiant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Etudiant{% endblock %}

{% block body %}
    <h4> <a href="{{ path('etudiant_index') }}">Voire la  liste des Etudiants</a>
    </h4>
    {{ include('etudiant/_form.html.twig') }}


{% endblock %}

templates/etudiant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etudiant{% endblock %}

{% block body %}
    <h1>Etudiant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ etudiant.id }}</td>
            </tr>
            <tr>
                <th>Matricule</th>
                <td>{{ etudiant.matricule }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ etudiant.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ etudiant.prenom }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ etudiant.telephone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ etudiant.email }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ etudiant.dateNaissance ? etudiant.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Type_etudiant</th>
                <td>{{ etudiant.typeEtudiant }}</td>
            </tr>
            <tr>
                <th>Type_bourse</th>
                <td>{{ etudiant.typeBourse }}</td>
            </tr>
            <tr>
                <th>Adrese</th>
                <td>{{ etudiant.adrese }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('etudiant_index') }}">back to list</a>

    <a href="{{ path('etudiant_edit', {'id': etudiant.id}) }}">edit</a>

    {{ include('etudiant/_delete_form.html.twig') }}
{% endblock %}